### ISSUE TITLE
Suggestion - Player Meta

### ISSUE THREAD

**Issue by NathanERP** [Topnetworks/qb-armor#1]
You could use the meta data for armor instead of adding a new column to the database as it is already there.

**Comment by Topnetworks** [comment]
> You could use the meta data for armor instead of adding a new column to the database as it is already there.

So we did had a talk about this and the metadata is not being used in qbcore.. its used in the qb-ambulancejob but thats it.. and im sure its going to be removed from metadata, This was just a easy option to get it working.

**Comment by Topnetworks** [comment]
Ok updated to use meta.
